site_name: CGraph
site_description: CGraph Documentation
site_url: https://cgraph.io
dev_addr: 0.0.0.0:8000

repo_name: 'GitHub'
repo_url: 'https://github.com/mcevoyinit/cgraph'

# https://squidfunk.github.io/mkdocs-material/
theme:
  name: 'material'
  language: en
  include_sidebar: true
  # favicon
  # logo
  feature:
    tabs: false
  palette:
    scheme: preference
    primary: 'red'
    accent: 'red'
  i18n:
    prev: 'Previous'
    next: 'Next'

# https://squidfunk.github.io/mkdocs-material/extensions/admonition/
# https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed
  - pymdownx.snippets:
      check_paths: true
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aPureBase/KGraphQL
    - icon: fontawesome/brands/slack
      link: https://kotlinlang.slack.com/messages/kgraphql

nav:
  - 'Overview': index.md
  - 'The Why': why.md
  - 'Concepts' :
      - 'The Graph' : concepts/graph.md
      - 'DGraph' : concepts/dgraph.md
      - 'Domain Data' : concepts/domain-data.md
      - 'Productivity' : concepts/productivity.md
  - 'Solution':
      - 'CorDapp':
         - 'The Core' : cordapp/core.md
         - 'CGraph JS' : cordapp/js.md
         - 'IOU Example': cordapp/example.md
      - 'Architecture': architecture/solution.md
  - 'Installation' : installation.md
  - 'Future': future.md
  - 'FAQ': faq.md

